version: '3.3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  sampledb:
    image: postgres:13.4-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: logstore
      POSTGRES_USER: postgres
    ports:
      - 5433:5432

  adminer:
    image: adminer:4.7.9
    restart: always
    ports:
      - 8111:8080

  app:
    image: logstore
    ports:
      - 8088:8080
    environment:
      DB_URL: jdbc:postgresql://sampledb:5432/logstore
      DB_USER: postgres
      DB_PASSWORD: 1234567
