version: '3.3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  sampledb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: postgres
      POSTGRES_DB: logstore

  adminer:
    image: adminer:4.7.9
    restart: always
    ports:
      - 8111:8080

  app:
    image: logstoredocker
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://sampledb:5432/logstore
      DB_USER: postgres
      DB_PASSWORD: 1234567